require("plugin_config.colorscheme")
require("plugin_config.lualine")
require("plugin_config.nvim-tree")
require("plugin_config.treesitter")
require("plugin_config.auto-pairs")
require("plugin_config.completions")
require("plugin_config.lsp-config")
require("plugin_config.bufferline")
require("plugin_config.nvim-comment")
-- require("plugin_config.indent-blankline")
require("plugin_config.toggle-term")
require("plugin_config.devicon")
require("plugin_config.telescope")
require("plugin_config.auto-tags")
